# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"

# Manual Edit This
# Note: Replace with main domain then, uncomment the line
baseURL = "https://delimaresidences.com/"

defaultContentLanguage = "id"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

buildDrafts = false
buildFuture = false

# Manual Edit This
# Note: Change with appropriate Google Analytics' GA4
# then, uncomment the line
googleAnalytics = "G-HCZBZ29N7S"

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]
