colorScheme = "foxautodetailing"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = false
mainSections = ["paket"]

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "background"
homepageImage = "img/DSCF9142-9.jpg"
showRecent = false
showRecentItems = "6"
showMoreLink = false
showMoreLinkDest = "/blowfish_artist/posts"
cardView = true
cardViewScreenWidth = ""
layoutBackgroundBlur = true

[article]
showDateUpdated = true
showAuthor = true
showHero = true
heroStyle = "background"
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = true
showWordCount = false
showSummary = true
# sharingLinks = [
#     "linkedin",
#     "twitter",
#     "whatsapp",
#     "pinterest",
#     "reddit",
#     "facebook",
#     "email",
# ]

[list]
showHero = true
heroStyle = "background"
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = false
cardView = true
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[firebase]

[fathomAnalytics]

[verification]
